plugins {
	alias(libs.plugins.spring.dependency.management)
	alias(libs.plugins.jacoco)
	alias(libs.plugins.java)
}

dependencies {
	annotationProcessor libs.lombok
	implementation project(':core')
	implementation libs.lombok
	implementation libs.spring.boot.starter.security
	implementation libs.spring.boot.starter.web
	testImplementation libs.junit.api
	testImplementation libs.junit.engine
	testImplementation libs.mockito.core
	testImplementation libs.mockito.junit
	testImplementation libs.assertj.core
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

