Layout/LineLength:
  Exclude:
    - '**/*'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'
