//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::book_suggestions::Entity as BookSuggestions;
pub use super::books::Entity as Books;
pub use super::events::Entity as Events;
pub use super::users::Entity as Users;
pub use super::votes::Entity as Votes;
