# frozen_string_literal: true

# Password model. Contains the password hash for a user, the salt used to generate the hash, and the hash algorithm used to generate the hash. The password hash is generated by the `has_secure_password` method provided by Rails.
class Password < ApplicationRecord
  has_secure_password

  belongs_to :user
end
