name: BookClub CI/CD workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: build/libs/*.jar

  test:
    needs: assemble
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/
      - name: Test with Gradle
        run: ./gradlew test integrationTest jacocoTestReport sonar
        env:
          DATABASE_URL: 'jdbc:h2:mem:testdb'
          PORT: '8080'
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: build/reports/tests/**

